blank_issues_enabled: true
contact_links:
  - name: Discussions
    url: https://github.com/CycloneDX/cdxgen/discussions
    about: Please ask and answer questions here.
  - name: Specification Discussions
    url: https://github.com/CycloneDX/specification/discussions
    about: Questions and comments about the CycloneDX specification here.
