name: docker tests

on:
  push:
    branches:
      - master
      - feature/*
      - release/*
  workflow_dispatch:

jobs:
  build:
    runs-on: [ubuntu-20.04]

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build and test
        run: |
          npm install
          npm run build --if-present
          npm test
          mkdir -p bomresults
        env:
          CI: true
      - name: dockertests
        run: |
          bin/cdxgen phpmyadmin@sha256:1092481630056189e43cc0fe66fd01defcc9334d78ab4611b22f65e9a39869bd -o bomresults/bom-phpmyadmin.json
          bin/cdxgen shiftleft/scan-slim -o bomresults/bom-scanslim.json -t docker
          bin/cdxgen redmine@sha256:a5c5f8a64a0d9a436a0a6941bc3fb156be0c89996add834fe33b66ebeed2439e -o bomresults/bom-redmine.json
          bin/cdxgen rocket.chat@sha256:379f7afa0e67497c363ac9a9b3e7e6a6d31deee228233307c987e4a0c68b28e6 -o bomresults/bom-rocket.json
          ls -ltr bomresults
      - uses: actions/upload-artifact@v1
        with:
          name: bomresults
          path: bomresults
